#pragma once

extern "C"

const SDL_ALPHA_OPAQUE = 255
const SDL_ALPHA_OPAQUE_FLOAT = 1.0f
const SDL_ALPHA_TRANSPARENT = 0
const SDL_ALPHA_TRANSPARENT_FLOAT = 0.0f

type SDL_PIXELTYPE as long
enum
	SDL_PIXELTYPE_UNKNOWN
	SDL_PIXELTYPE_INDEX1
	SDL_PIXELTYPE_INDEX4
	SDL_PIXELTYPE_INDEX8
	SDL_PIXELTYPE_PACKED8
	SDL_PIXELTYPE_PACKED16
	SDL_PIXELTYPE_PACKED32
	SDL_PIXELTYPE_ARRAYU8
	SDL_PIXELTYPE_ARRAYU16
	SDL_PIXELTYPE_ARRAYU32
	SDL_PIXELTYPE_ARRAYF16
	SDL_PIXELTYPE_ARRAYF32
	SDL_PIXELTYPE_INDEX2
end enum

type SDL_BitmapOrder as long
enum
	SDL_BITMAPORDER_NONE
	SDL_BITMAPORDER_4321
	SDL_BITMAPORDER_1234
end enum

type SDL_PackedOrder as long
enum
	SDL_PACKEDORDER_NONE
	SDL_PACKEDORDER_XRGB
	SDL_PACKEDORDER_RGBX
	SDL_PACKEDORDER_ARGB
	SDL_PACKEDORDER_RGBA
	SDL_PACKEDORDER_XBGR
	SDL_PACKEDORDER_BGRX
	SDL_PACKEDORDER_ABGR
	SDL_PACKEDORDER_BGRA
end enum

type SDL_ArrayOrder as long
enum
	SDL_ARRAYORDER_NONE
	SDL_ARRAYORDER_RGB
	SDL_ARRAYORDER_RGBA
	SDL_ARRAYORDER_ARGB
	SDL_ARRAYORDER_BGR
	SDL_ARRAYORDER_BGRA
	SDL_ARRAYORDER_ABGR
end enum

type SDL_PackedLayout as long
enum
	SDL_PACKEDLAYOUT_NONE
	SDL_PACKEDLAYOUT_332
	SDL_PACKEDLAYOUT_4444
	SDL_PACKEDLAYOUT_1555
	SDL_PACKEDLAYOUT_5551
	SDL_PACKEDLAYOUT_565
	SDL_PACKEDLAYOUT_8888
	SDL_PACKEDLAYOUT_2101010
	SDL_PACKEDLAYOUT_1010102
end enum

#define SDL_DEFINE_PIXELFOURCC(A, B, C, D) SDL_FOURCC(A, B, C, D)
#define SDL_DEFINE_PIXELFORMAT(type, order, layout, bits, bytes) _
    ((1 shl 28) or ((type) shl 24) or ((order) shl 20) or ((layout) shl 16) or _
    ((bits) shl 8) or ((bytes) shl 0))

#define SDL_PIXELFLAG(format) (((format) shr 28) and &h0F)
#define SDL_PIXELTYPE_(format) (((format) shr 24) and &h0F)
#define SDL_PIXELORDER(format) (((format) shr 20) and &h0F)
#define SDL_PIXELLAYOUT(format) (((format) shr 16) and &h0F)
#define SDL_BITSPERPIXEL(format) iif(SDL_ISPIXELFORMAT_FOURCC(format), 0, ((format) shr 8) and &hFF)
#define SDL_BYTESPERPIXEL(format) iif(SDL_ISPIXELFORMAT_FOURCC(format), _
            iif((format) = SDL_PIXELFORMAT_YUY2) orelse _
                ((format) = SDL_PIXELFORMAT_UYVY) orelse _
                ((format) = SDL_PIXELFORMAT_YVYU) orelse _
            iif(((format) = SDL_PIXELFORMAT_P010), 2, 1), ((format) shr 0) and &hFF)

#define SDL_ISPIXELFORMAT_INDEXED(format) ((SDL_ISPIXELFORMAT_FOURCC(format) = 0) andalso ((((SDL_PIXELTYPE_(format) = SDL_PIXELTYPE_INDEX1) orelse (SDL_PIXELTYPE_(format) = SDL_PIXELTYPE_INDEX2)) orelse (SDL_PIXELTYPE_(format) = SDL_PIXELTYPE_INDEX4)) orelse (SDL_PIXELTYPE_(format) = SDL_PIXELTYPE_INDEX8)))
#define SDL_ISPIXELFORMAT_PACKED(format) ((SDL_ISPIXELFORMAT_FOURCC(format) = 0) andalso (((SDL_PIXELTYPE_(format) = SDL_PIXELTYPE_PACKED8) orelse (SDL_PIXELTYPE_(format) = SDL_PIXELTYPE_PACKED16)) orelse (SDL_PIXELTYPE_(format) = SDL_PIXELTYPE_PACKED32)))
#define SDL_ISPIXELFORMAT_ARRAY(format) ((SDL_ISPIXELFORMAT_FOURCC(format) = 0) andalso (((((SDL_PIXELTYPE_(format) = SDL_PIXELTYPE_ARRAYU8) orelse (SDL_PIXELTYPE_(format) = SDL_PIXELTYPE_ARRAYU16)) orelse (SDL_PIXELTYPE_(format) = SDL_PIXELTYPE_ARRAYU32)) orelse (SDL_PIXELTYPE_(format) = SDL_PIXELTYPE_ARRAYF16)) orelse (SDL_PIXELTYPE_(format) = SDL_PIXELTYPE_ARRAYF32)))
#define SDL_ISPIXELFORMAT_ALPHA(format) (SDL_ISPIXELFORMAT_PACKED(format) andalso ((((SDL_PIXELORDER(format) = SDL_PACKEDORDER_ARGB) orelse (SDL_PIXELORDER(format) = SDL_PACKEDORDER_RGBA)) orelse (SDL_PIXELORDER(format) = SDL_PACKEDORDER_ABGR)) orelse (SDL_PIXELORDER(format) = SDL_PACKEDORDER_BGRA)))
#define SDL_ISPIXELFORMAT_10BIT(format) ((SDL_ISPIXELFORMAT_FOURCC(format) = 0) andalso ((SDL_PIXELTYPE_(format) = SDL_PIXELTYPE_PACKED32) andalso (SDL_PIXELLAYOUT(format) = SDL_PACKEDLAYOUT_2101010)))
#define SDL_ISPIXELFORMAT_FLOAT(format) ((SDL_ISPIXELFORMAT_FOURCC(format) = 0) andalso ((SDL_PIXELTYPE_(format) = SDL_PIXELTYPE_ARRAYF16) orelse (SDL_PIXELTYPE_(format) = SDL_PIXELTYPE_ARRAYF32)))
#define SDL_ISPIXELFORMAT_FOURCC(format) ((format) andalso (SDL_PIXELFLAG(format) <> 1))

type SDL_PixelFormat as long
enum
	SDL_PIXELFORMAT_UNKNOWN = 0
	SDL_PIXELFORMAT_INDEX1LSB = &h11100100u
	SDL_PIXELFORMAT_INDEX1MSB = &h11200100u
	SDL_PIXELFORMAT_INDEX2LSB = &h1c100200u
	SDL_PIXELFORMAT_INDEX2MSB = &h1c200200u
	SDL_PIXELFORMAT_INDEX4LSB = &h12100400u
	SDL_PIXELFORMAT_INDEX4MSB = &h12200400u
	SDL_PIXELFORMAT_INDEX8 = &h13000801u
	SDL_PIXELFORMAT_RGB332 = &h14110801u
	SDL_PIXELFORMAT_XRGB4444 = &h15120c02u
	SDL_PIXELFORMAT_XBGR4444 = &h15520c02u
	SDL_PIXELFORMAT_XRGB1555 = &h15130f02u
	SDL_PIXELFORMAT_XBGR1555 = &h15530f02u
	SDL_PIXELFORMAT_ARGB4444 = &h15321002u
	SDL_PIXELFORMAT_RGBA4444 = &h15421002u
	SDL_PIXELFORMAT_ABGR4444 = &h15721002u
	SDL_PIXELFORMAT_BGRA4444 = &h15821002u
	SDL_PIXELFORMAT_ARGB1555 = &h15331002u
	SDL_PIXELFORMAT_RGBA5551 = &h15441002u
	SDL_PIXELFORMAT_ABGR1555 = &h15731002u
	SDL_PIXELFORMAT_BGRA5551 = &h15841002u
	SDL_PIXELFORMAT_RGB565 = &h15151002u
	SDL_PIXELFORMAT_BGR565 = &h15551002u
	SDL_PIXELFORMAT_RGB24 = &h17101803u
	SDL_PIXELFORMAT_BGR24 = &h17401803u
	SDL_PIXELFORMAT_XRGB8888 = &h16161804u
	SDL_PIXELFORMAT_RGBX8888 = &h16261804u
	SDL_PIXELFORMAT_XBGR8888 = &h16561804u
	SDL_PIXELFORMAT_BGRX8888 = &h16661804u
	SDL_PIXELFORMAT_ARGB8888 = &h16362004u
	SDL_PIXELFORMAT_RGBA8888 = &h16462004u
	SDL_PIXELFORMAT_ABGR8888 = &h16762004u
	SDL_PIXELFORMAT_BGRA8888 = &h16862004u
	SDL_PIXELFORMAT_XRGB2101010 = &h16172004u
	SDL_PIXELFORMAT_XBGR2101010 = &h16572004u
	SDL_PIXELFORMAT_ARGB2101010 = &h16372004u
	SDL_PIXELFORMAT_ABGR2101010 = &h16772004u
	SDL_PIXELFORMAT_RGB48 = &h18103006u
	SDL_PIXELFORMAT_BGR48 = &h18403006u
	SDL_PIXELFORMAT_RGBA64 = &h18204008u
	SDL_PIXELFORMAT_ARGB64 = &h18304008u
	SDL_PIXELFORMAT_BGRA64 = &h18504008u
	SDL_PIXELFORMAT_ABGR64 = &h18604008u
	SDL_PIXELFORMAT_RGB48_FLOAT = &h1a103006u
	SDL_PIXELFORMAT_BGR48_FLOAT = &h1a403006u
	SDL_PIXELFORMAT_RGBA64_FLOAT = &h1a204008u
	SDL_PIXELFORMAT_ARGB64_FLOAT = &h1a304008u
	SDL_PIXELFORMAT_BGRA64_FLOAT = &h1a504008u
	SDL_PIXELFORMAT_ABGR64_FLOAT = &h1a604008u
	SDL_PIXELFORMAT_RGB96_FLOAT = &h1b10600cu
	SDL_PIXELFORMAT_BGR96_FLOAT = &h1b40600cu
	SDL_PIXELFORMAT_RGBA128_FLOAT = &h1b208010u
	SDL_PIXELFORMAT_ARGB128_FLOAT = &h1b308010u
	SDL_PIXELFORMAT_BGRA128_FLOAT = &h1b508010u
	SDL_PIXELFORMAT_ABGR128_FLOAT = &h1b608010u
	SDL_PIXELFORMAT_YV12 = &h32315659u
	SDL_PIXELFORMAT_IYUV = &h56555949u
	SDL_PIXELFORMAT_YUY2 = &h32595559u
	SDL_PIXELFORMAT_UYVY = &h59565955u
	SDL_PIXELFORMAT_YVYU = &h55595659u
	SDL_PIXELFORMAT_NV12 = &h3231564eu
	SDL_PIXELFORMAT_NV21 = &h3132564eu
	SDL_PIXELFORMAT_P010 = &h30313050u
	SDL_PIXELFORMAT_EXTERNAL_OES = &h2053454fu
    
    SDL_PIXELFORMAT_MJPG = &h47504a4du

	
  #if SDL_BYTEORDER = SDL_BIG_ENDIAN
    SDL_PIXELFORMAT_RGBA32 = SDL_PIXELFORMAT_RGBA8888
    SDL_PIXELFORMAT_ARGB32 = SDL_PIXELFORMAT_ARGB8888
    SDL_PIXELFORMAT_BGRA32 = SDL_PIXELFORMAT_BGRA8888
    SDL_PIXELFORMAT_ABGR32 = SDL_PIXELFORMAT_ABGR8888
    SDL_PIXELFORMAT_RGBX32 = SDL_PIXELFORMAT_RGBX8888
    SDL_PIXELFORMAT_XRGB32 = SDL_PIXELFORMAT_XRGB8888
    SDL_PIXELFORMAT_BGRX32 = SDL_PIXELFORMAT_BGRX8888
    SDL_PIXELFORMAT_XBGR32 = SDL_PIXELFORMAT_XBGR8888
  #else
    SDL_PIXELFORMAT_RGBA32 = SDL_PIXELFORMAT_ABGR8888
    SDL_PIXELFORMAT_ARGB32 = SDL_PIXELFORMAT_BGRA8888
    SDL_PIXELFORMAT_BGRA32 = SDL_PIXELFORMAT_ARGB8888
    SDL_PIXELFORMAT_ABGR32 = SDL_PIXELFORMAT_RGBA8888
    SDL_PIXELFORMAT_RGBX32 = SDL_PIXELFORMAT_XBGR8888
    SDL_PIXELFORMAT_XRGB32 = SDL_PIXELFORMAT_BGRX8888
    SDL_PIXELFORMAT_BGRX32 = SDL_PIXELFORMAT_XRGB8888
    SDL_PIXELFORMAT_XBGR32 = SDL_PIXELFORMAT_RGBX8888
  #endif
end enum

type SDL_ColorType as long
enum
	SDL_COLOR_TYPE_UNKNOWN = 0
	SDL_COLOR_TYPE_RGB = 1
	SDL_COLOR_TYPE_YCBCR = 2
end enum

type SDL_ColorRange as long
enum
	SDL_COLOR_RANGE_UNKNOWN = 0
	SDL_COLOR_RANGE_LIMITED = 1
	SDL_COLOR_RANGE_FULL = 2
end enum

type SDL_ColorPrimaries as long
enum
	SDL_COLOR_PRIMARIES_UNKNOWN = 0
	SDL_COLOR_PRIMARIES_BT709 = 1
	SDL_COLOR_PRIMARIES_UNSPECIFIED = 2
	SDL_COLOR_PRIMARIES_BT470M = 4
	SDL_COLOR_PRIMARIES_BT470BG = 5
	SDL_COLOR_PRIMARIES_BT601 = 6
	SDL_COLOR_PRIMARIES_SMPTE240 = 7
	SDL_COLOR_PRIMARIES_GENERIC_FILM = 8
	SDL_COLOR_PRIMARIES_BT2020 = 9
	SDL_COLOR_PRIMARIES_XYZ = 10
	SDL_COLOR_PRIMARIES_SMPTE431 = 11
	SDL_COLOR_PRIMARIES_SMPTE432 = 12
	SDL_COLOR_PRIMARIES_EBU3213 = 22
	SDL_COLOR_PRIMARIES_CUSTOM = 31
end enum

type SDL_TransferCharacteristics as long
enum
	SDL_TRANSFER_CHARACTERISTICS_UNKNOWN = 0
	SDL_TRANSFER_CHARACTERISTICS_BT709 = 1
	SDL_TRANSFER_CHARACTERISTICS_UNSPECIFIED = 2
	SDL_TRANSFER_CHARACTERISTICS_GAMMA22 = 4
	SDL_TRANSFER_CHARACTERISTICS_GAMMA28 = 5
	SDL_TRANSFER_CHARACTERISTICS_BT601 = 6
	SDL_TRANSFER_CHARACTERISTICS_SMPTE240 = 7
	SDL_TRANSFER_CHARACTERISTICS_LINEAR = 8
	SDL_TRANSFER_CHARACTERISTICS_LOG100 = 9
	SDL_TRANSFER_CHARACTERISTICS_LOG100_SQRT10 = 10
	SDL_TRANSFER_CHARACTERISTICS_IEC61966 = 11
	SDL_TRANSFER_CHARACTERISTICS_BT1361 = 12
	SDL_TRANSFER_CHARACTERISTICS_SRGB = 13
	SDL_TRANSFER_CHARACTERISTICS_BT2020_10BIT = 14
	SDL_TRANSFER_CHARACTERISTICS_BT2020_12BIT = 15
	SDL_TRANSFER_CHARACTERISTICS_PQ = 16
	SDL_TRANSFER_CHARACTERISTICS_SMPTE428 = 17
	SDL_TRANSFER_CHARACTERISTICS_HLG = 18
	SDL_TRANSFER_CHARACTERISTICS_CUSTOM = 31
end enum

type SDL_MatrixCoefficients as long
enum
	SDL_MATRIX_COEFFICIENTS_IDENTITY = 0
	SDL_MATRIX_COEFFICIENTS_BT709 = 1
	SDL_MATRIX_COEFFICIENTS_UNSPECIFIED = 2
	SDL_MATRIX_COEFFICIENTS_FCC = 4
	SDL_MATRIX_COEFFICIENTS_BT470BG = 5
	SDL_MATRIX_COEFFICIENTS_BT601 = 6
	SDL_MATRIX_COEFFICIENTS_SMPTE240 = 7
	SDL_MATRIX_COEFFICIENTS_YCGCO = 8
	SDL_MATRIX_COEFFICIENTS_BT2020_NCL = 9
	SDL_MATRIX_COEFFICIENTS_BT2020_CL = 10
	SDL_MATRIX_COEFFICIENTS_SMPTE2085 = 11
	SDL_MATRIX_COEFFICIENTS_CHROMA_DERIVED_NCL = 12
	SDL_MATRIX_COEFFICIENTS_CHROMA_DERIVED_CL = 13
	SDL_MATRIX_COEFFICIENTS_ICTCP = 14
	SDL_MATRIX_COEFFICIENTS_CUSTOM = 31
end enum

type SDL_ChromaLocation as long
enum
	SDL_CHROMA_LOCATION_NONE = 0
	SDL_CHROMA_LOCATION_LEFT = 1
	SDL_CHROMA_LOCATION_CENTER = 2
	SDL_CHROMA_LOCATION_TOPLEFT = 3
end enum

#define SDL_DEFINE_COLORSPACE(type, range, primaries, transfer, matrix, chroma) ((((((cast(Uint32, (type)) shl 28) or (cast(Uint32, (range)) shl 24)) or (cast(Uint32, (chroma)) shl 20)) or (cast(Uint32, (primaries)) shl 10)) or (cast(Uint32, (transfer)) shl 5)) or (cast(Uint32, (matrix)) shl 0))

#define SDL_COLORSPACETYPE(cspace) cast(SDL_ColorType, ((cspace) shr 28) and &h0F)
#define SDL_COLORSPACERANGE(cspace) cast(SDL_ColorRange, ((cspace) shr 24) and &h0F)
#define SDL_COLORSPACECHROMA(cspace) cast(SDL_ChromaLocation, ((cspace) shr 20) and &h0F)
#define SDL_COLORSPACEPRIMARIES(cspace) cast(SDL_ColorPrimaries, ((cspace) shr 10) and &h1F)
#define SDL_COLORSPACETRANSFER(cspace) cast(SDL_TransferCharacteristics, ((cspace) shr 5) and &h1F)
#define SDL_COLORSPACEMATRIX(cspace) cast(SDL_MatrixCoefficients, (cspace) and &h1F)

#define SDL_ISCOLORSPACE_MATRIX_BT601(cspace) ((SDL_COLORSPACEMATRIX(cspace) = SDL_MATRIX_COEFFICIENTS_BT601) orelse (SDL_COLORSPACEMATRIX(cspace) = SDL_MATRIX_COEFFICIENTS_BT470BG))
#define SDL_ISCOLORSPACE_MATRIX_BT709(cspace) (SDL_COLORSPACEMATRIX(cspace) = SDL_MATRIX_COEFFICIENTS_BT709)
#define SDL_ISCOLORSPACE_MATRIX_BT2020_NCL(cspace) (SDL_COLORSPACEMATRIX(cspace) = SDL_MATRIX_COEFFICIENTS_BT2020_NCL)
#define SDL_ISCOLORSPACE_LIMITED_RANGE(cspace) (SDL_COLORSPACERANGE(cspace) <> SDL_COLOR_RANGE_FULL)
#define SDL_ISCOLORSPACE_FULL_RANGE(cspace) (SDL_COLORSPACERANGE(cspace) = SDL_COLOR_RANGE_FULL)

type SDL_Colorspace as long
enum
	SDL_COLORSPACE_UNKNOWN = 0
	SDL_COLORSPACE_SRGB = &h120005a0u
	SDL_COLORSPACE_SRGB_LINEAR = &h12000500u
	SDL_COLORSPACE_HDR10 = &h12002600u
	SDL_COLORSPACE_JPEG = &h220004c6u
	SDL_COLORSPACE_BT601_LIMITED = &h211018c6u
	SDL_COLORSPACE_BT601_FULL = &h221018c6u
	SDL_COLORSPACE_BT709_LIMITED = &h21100421u
	SDL_COLORSPACE_BT709_FULL = &h22100421u
	SDL_COLORSPACE_BT2020_LIMITED = &h21102609u
	SDL_COLORSPACE_BT2020_FULL = &h22102609u
	SDL_COLORSPACE_RGB_DEFAULT = SDL_COLORSPACE_SRGB
	SDL_COLORSPACE_YUV_DEFAULT = SDL_COLORSPACE_JPEG
end enum

type SDL_Color
	r as Uint8
	g as Uint8
	b as Uint8
	a as Uint8
end type

type SDL_FColor
	r as single
	g as single
	b as single
	a as single
end type

type SDL_Palette
	ncolors as long
	colors as SDL_Color ptr
	version as Uint32
	refcount as long
end type

type SDL_PixelFormatDetails
	format as SDL_PixelFormat
	bits_per_pixel as Uint8
	bytes_per_pixel as Uint8
	padding(0 to 1) as Uint8
	Rmask as Uint32
	Gmask as Uint32
	Bmask as Uint32
	Amask as Uint32
	Rbits as Uint8
	Gbits as Uint8
	Bbits as Uint8
	Abits as Uint8
	Rshift as Uint8
	Gshift as Uint8
	Bshift as Uint8
	Ashift as Uint8
end type

declare function SDL_GetPixelFormatName(byval format as SDL_PixelFormat) as const zstring ptr
declare function SDL_GetMasksForPixelFormat(byval format as SDL_PixelFormat, byval bpp as long ptr, byval Rmask as Uint32 ptr, byval Gmask as Uint32 ptr, byval Bmask as Uint32 ptr, byval Amask as Uint32 ptr) as boolean
declare function SDL_GetPixelFormatForMasks(byval bpp as long, byval Rmask as Uint32, byval Gmask as Uint32, byval Bmask as Uint32, byval Amask as Uint32) as SDL_PixelFormat
declare function SDL_GetPixelFormatDetails(byval format as SDL_PixelFormat) as const SDL_PixelFormatDetails ptr
declare function SDL_CreatePalette(byval ncolors as long) as SDL_Palette ptr
declare function SDL_SetPaletteColors(byval palette as SDL_Palette ptr, byval colors as const SDL_Color ptr, byval firstcolor as long, byval ncolors as long) as boolean
declare sub SDL_DestroyPalette(byval palette as SDL_Palette ptr)
declare function SDL_MapRGB(byval format as const SDL_PixelFormatDetails ptr, byval palette as const SDL_Palette ptr, byval r as Uint8, byval g as Uint8, byval b as Uint8) as Uint32
declare function SDL_MapRGBA(byval format as const SDL_PixelFormatDetails ptr, byval palette as const SDL_Palette ptr, byval r as Uint8, byval g as Uint8, byval b as Uint8, byval a as Uint8) as Uint32
declare sub SDL_GetRGB(byval pixel as Uint32, byval format as const SDL_PixelFormatDetails ptr, byval palette as const SDL_Palette ptr, byval r as Uint8 ptr, byval g as Uint8 ptr, byval b as Uint8 ptr)
declare sub SDL_GetRGBA(byval pixel as Uint32, byval format as const SDL_PixelFormatDetails ptr, byval palette as const SDL_Palette ptr, byval r as Uint8 ptr, byval g as Uint8 ptr, byval b as Uint8 ptr, byval a as Uint8 ptr)

end extern
